name = "MagnusNudecker"
uuid = "e9b6de53-3b1a-4441-99c9-f3d1ba164032"
authors = ["Giuseppe Ragusa <giuseppe.ragusa@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.1"
